#!/bin/bash

# yum packages
sudo yum update -y 
sudo yum install -y git docker

# setup docker
sudo systemctl enable docker
sudo gpasswd -a $USER docker
newgrp docker

# docker compose
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
  -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

# change timezone
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
