#!/bin/bash

# yum packages
sudo yum update -y 
sudo yum install -y git docker

# setup docker
usermod -a -G docker ec2-user
newgrp docker
sudo systemctl start docker
sudo systemctl enable docker

# docker compose
DOCKER_CONFIG=/home/ec2-user/.docker
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
  -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

sudo chown -R ec2-user:ec2-user $DOCKER_CONFIG

# certbot
sudo amazon-linux-extras install epel -y
sudo yum install certbot -y
